package com.adityaamolbavadekar.gonotes.usecases.search

import androidx.fragment.app.FragmentActivity
import com.adityaamolbavadekar.gonotes.GoNotes
import com.adityaamolbavadekar.gonotes.features.search.source.SearchItemModel

class SearchUtils {

    class Creator {
        private var _noteReferenceId: Int? = null
        private var _title: String = ""
        private var _body: String = ""

        fun withNoteReferenceId(id: Int): Creator {
            this._noteReferenceId = id
            return this
        }

        fun withTitle(text: String): Creator {
            this._title = text
            return this
        }

        fun withBody(text: String): Creator {
            this._body = text
            return this
        }

        fun build(): SearchItemModel {
            if (_noteReferenceId == null) {
                throw NullPointerException("No value passed for noteReferenceId. Set it with SearchUtils.Creator().withNoteReferenceId(id:Int)")
            } else {
                return SearchItemModel(
                    id = 0, /*This will be auto generated by room*/
                    suggestedNoteReferenceId = _noteReferenceId!!,
                    title = _title,
                    body = _body
                )
            }
        }

        suspend fun save(fragmentActivity: FragmentActivity) {
            val repo = (fragmentActivity.application as GoNotes).searchHistoryRepository
            repo.insertIntoSearchHistory(build())
        }

    }

}